-- V5: multi-company auth + Company / Language VVDs.
--
-- Pivots the demo from single-tenant email login to multi-company username
-- + companyCode login (CSnx-shaped). The `customer` table is kept for now;
-- V8 drops it after the Java code stops referencing it.
--
-- Conceptual reference (DO NOT read from CSnx at runtime):
--   C:\software\projects\CSnx\src\za\co\csnx\model\csnx\Company.java   -> SCWT_COMPANY
--   C:\software\projects\CSnx\src\za\co\csnx\model\csnx\User.java      -> USERS

CREATE TABLE demoschema.company (
    cpy_cd          VARCHAR(8)      PRIMARY KEY,
    description     VARCHAR(255)    NOT NULL,
    active          BOOLEAN         NOT NULL DEFAULT TRUE,

    created_at      TIMESTAMPTZ     NOT NULL,
    updated_at      TIMESTAMPTZ     NOT NULL,
    created_by      VARCHAR(100),
    updated_by      VARCHAR(100),
    update_serial   BIGINT          NOT NULL DEFAULT 0
);

CREATE TABLE demoschema.app_user (
    cpy_cd              VARCHAR(8)   NOT NULL REFERENCES demoschema.company(cpy_cd),
    username            VARCHAR(64)  NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    full_name           VARCHAR(100) NOT NULL,
    language            VARCHAR(8)   NOT NULL DEFAULT 'EN',
    default_facility    VARCHAR(16),
    default_warehouse   VARCHAR(16),
    locked              BOOLEAN      NOT NULL DEFAULT FALSE,
    wcs_user            BOOLEAN      NOT NULL DEFAULT FALSE,

    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL,
    created_by          VARCHAR(100),
    updated_by          VARCHAR(100),
    update_serial       BIGINT       NOT NULL DEFAULT 0,

    PRIMARY KEY (cpy_cd, username)
);

CREATE INDEX idx_app_user_username ON demoschema.app_user (username);

-- Seed: one company, one user (`wcs` / wcs123!). The actual bcrypt hash is
-- inserted by AppUserSeeder (ApplicationRunner) on first boot so the hash is
-- generated by the same BCryptPasswordEncoder that validates it.
INSERT INTO demoschema.company (cpy_cd, description, active, created_at, updated_at, created_by)
VALUES ('WCS', 'WCS Demo Company', TRUE, NOW(), NOW(), 'system');

-- Seed the Company VVD so the pre-login dropdown has values + the post-login
-- engine sees Company in lookupData.
INSERT INTO demoschema.lookup_value (lookup_key, code, label, sort_order, created_at, updated_at, created_by)
VALUES
    ('Company', 'WCS', 'WCS Demo Company', 0, NOW(), NOW(), 'system');

-- Language VVD — `reportText.maintenance` form has a Language dropdown.
INSERT INTO demoschema.lookup_value (lookup_key, code, label, sort_order, created_at, updated_at, created_by)
VALUES
    ('Language', 'EN', 'English', 0, NOW(), NOW(), 'system'),
    ('Language', 'FR', 'French',  1, NOW(), NOW(), 'system'),
    ('Language', 'DE', 'German',  2, NOW(), NOW(), 'system');
